# Generated by Django 3.0.9 on 2021-11-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/', verbose_name='画像1')),
                ('image2', models.ImageField(upload_to='documents2/', verbose_name='画像2')),
            ],
        ),
    ]
